replicaCount: 1

image:
  repository: localhost:5001/grpc-server
  pullPolicy: Always
  tag: "latest"

service:
  name: grpc
  type: NodePort
  port: 8081
  nodePort: 30081

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

config:
  # Logging:
  #   LogLevel:
  #     Default: Debug
  #     Microsoft: Warning
  Kestrel:
    Endpoints:
      Grpc:
        Url: "http://localhost:8081"
        Protocols: Http2
  OpenMatch:
    FrontendHost: "http://open-match-frontend.open-match.svc.cluster.local"
    FrontendPort: 50504
