replicaCount: 1

image:
  repository: localhost:5001/game-server
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8082

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
